INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
INFO : Using neuron-nightly Package (Developer Version)
numprocs=80
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.
Warning: could not import interactive plotting functions; make sure the "bokeh" package is installed.

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Start time:  2021-07-04 06:58:17.088347

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Loading file data/v34_batch25/trial_2142/trial_2142_cfg.json ... 
Loading simConfig...
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py
Importing netParams from data/v34_batch25/v34_batch25_netParams.py

Creating network of 43 cell populations on 80 hosts...
  Number of cells on node 12: 162 
  Number of cells on node 0: 162 
  Done; cell creation time = 0.50 s.
Making connections...
  Number of cells on node 25: 162 
  Number of cells on node 11: 162 
  Number of cells on node 35: 161 
  Number of cells on node 68: 161 
  Number of cells on node 58: 161 
  Number of cells on node 76: 161 
  Number of cells on node 56: 161 
  Number of cells on node 79: 161 
  Number of cells on node 36: 161 
  Number of cells on node 43: 161 
  Number of cells on node 30: 161 
  Number of cells on node 18: 162 
  Number of cells on node 21: 162 
  Number of cells on node 64: 161 
  Number of cells on node 31: 161 
  Number of cells on node 17: 162 
  Number of cells on node 42: 161 
  Number of cells on node 77: 161 
  Number of cells on node 61: 161 
  Number of cells on node 38: 161 
  Number of cells on node 40: 161 
  Number of cells on node 51: 161 
  Number of cells on node 37: 161 
  Number of cells on node 16: 162 
  Number of cells on node 24: 162 
  Number of cells on node 20: 162 
  Number of cells on node 69: 161 
  Number of cells on node 45: 161 
  Number of cells on node 8: 162 
  Number of cells on node 53: 161 
  Number of cells on node 74: 161 
  Number of cells on node 23: 162 
  Number of cells on node 57: 161 
  Number of cells on node 10: 162 
  Number of cells on node 67: 161 
  Number of cells on node 54: 161 
  Number of cells on node 73: 161 
  Number of cells on node 55: 161 
  Number of cells on node 66: 161 
  Number of cells on node 33: 161 
  Number of cells on node 3: 162 
  Number of cells on node 75: 161 
  Number of cells on node 48: 161 
  Number of cells on node 63: 161 
  Number of cells on node 29: 161 
  Number of cells on node 7: 162 
  Number of cells on node 52: 161 
  Number of cells on node 46: 161 
  Number of cells on node 60: 161 
  Number of cells on node 39: 161 
  Number of cells on node 44: 161 
  Number of cells on node 14: 162 
  Number of cells on node 4: 162 
  Number of cells on node 27: 162 
  Number of cells on node 28: 161 
  Number of cells on node 41: 161 
  Number of cells on node 13: 162 
  Number of cells on node 26: 162 
  Number of cells on node 78: 161 
  Number of cells on node 72: 161 
  Number of cells on node 34: 161 
  Number of cells on node 70: 161 
  Number of cells on node 71: 161 
  Number of cells on node 6: 162 
  Number of cells on node 62: 161 
  Number of cells on node 1: 162 
  Number of cells on node 19: 162 
  Number of cells on node 65: 161 
  Number of cells on node 47: 161 
  Number of cells on node 59: 161 
  Number of cells on node 50: 161 
  Number of cells on node 32: 161 
  Number of cells on node 22: 162 
  Number of cells on node 15: 162 
  Number of cells on node 2: 162 
  Number of cells on node 49: 161 
  Number of cells on node 5: 162 
  Number of cells on node 9: 162 
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Distributing synapses based on subcellular connectivity rules...
  Number of connections on node 75: 165862 
  Number of synaptic contacts on node 75: 322707 
  Number of connections on node 63: 164360 
  Number of synaptic contacts on node 63: 319424 
  Number of connections on node 67: 163946 
  Number of synaptic contacts on node 67: 318793 
  Number of connections on node 41: 163399 
  Number of synaptic contacts on node 41: 317660 
  Number of connections on node 61: 164086 
  Number of synaptic contacts on node 61: 319212 
  Number of connections on node 42: 163731 
  Number of synaptic contacts on node 42: 318214 
  Number of connections on node 44: 163656 
  Number of synaptic contacts on node 44: 317931 
  Number of connections on node 71: 165643 
  Number of synaptic contacts on node 71: 322220 
  Number of connections on node 45: 163485 
  Number of synaptic contacts on node 45: 317666 
  Number of connections on node 64: 165172 
  Number of synaptic contacts on node 64: 321378 
  Number of connections on node 74: 166606 
  Number of synaptic contacts on node 74: 324042 
  Number of connections on node 60: 164278 
  Number of synaptic contacts on node 60: 319566 
  Number of connections on node 68: 164997 
  Number of synaptic contacts on node 68: 320878 
  Number of connections on node 72: 165424 
  Number of synaptic contacts on node 72: 322022 
  Number of connections on node 73: 166105 
  Number of synaptic contacts on node 73: 323101 
  Number of connections on node 70: 164379 
  Number of synaptic contacts on node 70: 319819 
  Number of connections on node 62: 164828 
  Number of synaptic contacts on node 62: 320612 
  Number of connections on node 43: 163544 
  Number of synaptic contacts on node 43: 317857 
  Number of connections on node 66: 165522 
  Number of synaptic contacts on node 66: 321761 
  Number of connections on node 69: 165206 
  Number of synaptic contacts on node 69: 321249 
  Number of connections on node 65: 165161 
  Number of synaptic contacts on node 65: 321184 
  Number of connections on node 5: 166030 
  Number of synaptic contacts on node 5: 323207 
  Number of connections on node 4: 166942 
  Number of synaptic contacts on node 4: 324772 
  Number of connections on node 2: 167267 
  Number of synaptic contacts on node 2: 325421 
  Number of connections on node 54: 164669 
  Number of synaptic contacts on node 54: 320609 
  Number of connections on node 3: 166935 
  Number of synaptic contacts on node 3: 324686 
  Number of connections on node 49: 164648 
  Number of synaptic contacts on node 49: 320301 
  Number of connections on node 50: 164767 
  Number of synaptic contacts on node 50: 320266 
  Number of connections on node 77: 166937 
  Number of synaptic contacts on node 77: 324751 
  Number of connections on node 57: 165034 
  Number of synaptic contacts on node 57: 320878 
  Number of connections on node 53: 164834 
  Number of synaptic contacts on node 53: 320827 
  Number of connections on node 56: 165480 
  Number of synaptic contacts on node 56: 321744 
  Number of connections on node 7: 166655 
  Number of synaptic contacts on node 7: 324310 
  Number of connections on node 8: 167207 
  Number of synaptic contacts on node 8: 325268 
  Number of connections on node 51: 165955 
  Number of synaptic contacts on node 51: 322624 
  Number of connections on node 0: 167429 
  Number of synaptic contacts on node 0: 325652 
  Number of connections on node 1: 167311 
  Number of synaptic contacts on node 1: 325401 
  Number of connections on node 76: 166850 
  Number of synaptic contacts on node 76: 324775 
  Number of connections on node 52: 164351 
  Number of synaptic contacts on node 52: 319823 
  Number of connections on node 55: 165358 
  Number of synaptic contacts on node 55: 321848 
  Number of connections on node 79: 167419 
  Number of synaptic contacts on node 79: 325852 
  Number of connections on node 6: 166637 
  Number of synaptic contacts on node 6: 324157 
  Number of connections on node 47: 165414 
  Number of synaptic contacts on node 47: 321722 
  Number of connections on node 78: 167420 
  Number of synaptic contacts on node 78: 325898 
  Number of connections on node 58: 166390 
  Number of synaptic contacts on node 58: 323531 
  Number of connections on node 59: 165799 
  Number of synaptic contacts on node 59: 322678 
  Number of connections on node 33: 165596 
  Number of synaptic contacts on node 33: 322015 
  Number of connections on node 48: 164465 
  Number of synaptic contacts on node 48: 319866 
  Number of connections on node 12: 166440 
  Number of synaptic contacts on node 12: 323815 
  Number of connections on node 34: 166118 
  Number of synaptic contacts on node 34: 323183 
  Number of connections on node 46: 165264 
  Number of synaptic contacts on node 46: 321271 
  Number of connections on node 11: 166434 
  Number of synaptic contacts on node 11: 323769 
  Number of connections on node 30: 165702 
  Number of synaptic contacts on node 30: 322092 
  Number of connections on node 13: 166599 
  Number of synaptic contacts on node 13: 324169 
  Number of connections on node 27: 166162 
  Number of synaptic contacts on node 27: 323173 
  Number of connections on node 10: 166846 
  Number of synaptic contacts on node 10: 324435 
  Number of connections on node 40: 164899 
  Number of synaptic contacts on node 40: 320776 
  Number of connections on node 9: 167172 
  Number of synaptic contacts on node 9: 325259 
  Number of connections on node 31: 165726 
  Number of synaptic contacts on node 31: 322280 
  Number of connections on node 36: 166193 
  Number of synaptic contacts on node 36: 323169 
  Number of connections on node 35: 166175 
  Number of synaptic contacts on node 35: 323153 
  Number of connections on node 32: 166224 
  Number of synaptic contacts on node 32: 323452 
  Number of connections on node 28: 165899 
  Number of synaptic contacts on node 28: 322619 
  Number of connections on node 37: 165982 
  Number of synaptic contacts on node 37: 322772 
  Number of connections on node 38: 165884 
  Number of synaptic contacts on node 38: 322585 
  Number of connections on node 29: 165556 
  Number of synaptic contacts on node 29: 322130 
  Number of connections on node 15: 168276 
  Number of synaptic contacts on node 15: 327658 
  Number of connections on node 23: 167244 
  Number of synaptic contacts on node 23: 325250 
  Number of connections on node 20: 167739 
  Number of synaptic contacts on node 20: 326234 
  Number of connections on node 16: 168027 
  Number of synaptic contacts on node 16: 326907 
  Number of connections on node 39: 166152 
  Number of synaptic contacts on node 39: 323252 
  Number of connections on node 21: 167763 
  Number of synaptic contacts on node 21: 326355 
  Number of connections on node 17: 168019 
  Number of synaptic contacts on node 17: 326899 
  Number of connections on node 24: 168154 
  Number of synaptic contacts on node 24: 326926 
  Number of connections on node 18: 168085 
  Number of synaptic contacts on node 18: 326884 
  Number of connections on node 22: 167125 
  Number of synaptic contacts on node 22: 325257 
  Number of connections on node 14: 168544 
  Number of synaptic contacts on node 14: 327888 
  Number of connections on node 19: 168549 
  Number of synaptic contacts on node 19: 327871 
  Number of connections on node 25: 168430 
  Number of synaptic contacts on node 25: 327668 
  Number of connections on node 26: 169336 
  Number of synaptic contacts on node 26: 329378 
  Done; cell connection time = 700.75 s.
Adding stims...
  Number of stims on node 44: 483 
  Number of stims on node 32: 483 
  Number of stims on node 40: 483 
  Number of stims on node 0: 486 
  Number of stims on node 22: 486 
  Number of stims on node 33: 483 
  Number of stims on node 23: 486 
  Number of stims on node 73: 483 
  Number of stims on node 16: 486 
  Number of stims on node 5: 486 
  Number of stims on node 54: 483 
  Number of stims on node 42: 483 
  Number of stims on node 55: 483 
  Number of stims on node 20: 486 
  Number of stims on node 6: 486 
  Number of stims on node 25: 486 
  Number of stims on node 49: 483 
  Number of stims on node 51: 483 
  Number of stims on node 36: 483 
  Number of stims on node 75: 483 
  Number of stims on node 64: 483 
  Number of stims on node 7: 486 
  Number of stims on node 61: 483 
  Number of stims on node 9: 486 
  Number of stims on node 18: 486 
  Number of stims on node 62: 483 
  Number of stims on node 15: 486 
  Number of stims on node 71: 483 
  Number of stims on node 74: 483 
  Number of stims on node 76: 483 
  Number of stims on node 63: 483 
  Number of stims on node 47: 483 
  Number of stims on node 48: 483 
  Number of stims on node 17: 486 
  Number of stims on node 8: 486 
  Number of stims on node 67: 483 
  Number of stims on node 27: 486 
  Number of stims on node 77: 483 
  Number of stims on node 37: 483 
  Number of stims on node 3: 486 
  Number of stims on node 52: 483 
  Number of stims on node 41: 483 
  Number of stims on node 21: 486 
  Number of stims on node 72: 483 
  Number of stims on node 14: 486 
  Number of stims on node 69: 483 
  Number of stims on node 66: 483 
  Number of stims on node 57: 483 
  Number of stims on node 31: 483 
  Number of stims on node 60: 483 
  Number of stims on node 45: 483 
  Number of stims on node 24: 486 
  Number of stims on node 30: 483 
  Number of stims on node 50: 483 
  Number of stims on node 13: 486 
  Number of stims on node 53: 483 
  Number of stims on node 29: 483 
  Number of stims on node 34: 483 
  Number of stims on node 46: 483 
  Number of stims on node 59: 483 
  Number of stims on node 68: 483 
  Number of stims on node 2: 486 
  Number of stims on node 26: 486 
  Number of stims on node 10: 486 
  Number of stims on node 35: 483 
  Number of stims on node 39: 483 
  Number of stims on node 65: 483 
  Number of stims on node 58: 483 
  Number of stims on node 19: 486 
  Number of stims on node 43: 483 
  Number of stims on node 12: 486 
  Number of stims on node 28: 483 
  Number of stims on node 1: 486 
  Number of stims on node 38: 483 
  Number of stims on node 78: 483 
  Number of stims on node 79: 483 
  Number of stims on node 4: 486 
  Number of stims on node 11: 486 
  Number of stims on node 56: 483 
  Number of stims on node 70: 483 
  Done; cell stims creation time = 1.98 s.
Recording 0 traces of 0 types on node 73
Recording 1 traces of 1 types on node 5
Recording 1 traces of 1 types on node 16
Recording 1 traces of 1 types on node 24
Recording 0 traces of 0 types on node 74
Recording 0 traces of 0 types on node 44
Recording 2 traces of 1 types on node 21
Recording 1 traces of 1 types on node 6
Recording 1 traces of 1 types on node 20
Recording 1 traces of 1 types on node 46
Recording 0 traces of 0 types on node 30
Recording 1 traces of 1 types on node 76
Recording 0 traces of 0 types on node 36
Recording 1 traces of 1 types on node 2
Recording 1 traces of 1 types on node 0
Recording 0 traces of 0 types on node 59
Recording 0 traces of 0 types on node 75
Recording 0 traces of 0 types on node 26
Recording 2 traces of 1 types on node 57
Recording 1 traces of 1 types on node 35
Recording 0 traces of 0 types on node 17
Recording 0 traces of 0 types on node 61
Recording 1 traces of 1 types on node 54
Recording 0 traces of 0 types on node 31
Recording 0 traces of 0 types on node 38
Recording 1 traces of 1 types on node 53
Recording 0 traces of 0 types on node 29
Recording 1 traces of 1 types on node 39
Recording 1 traces of 1 types on node 23
Recording 0 traces of 0 types on node 10
Recording 0 traces of 0 types on node 8
Recording 0 traces of 0 types on node 67
Recording 0 traces of 0 types on node 47
Recording 1 traces of 1 types on node 52
Recording 2 traces of 1 types on node 27
Recording 0 traces of 0 types on node 45
Recording 0 traces of 0 types on node 64
Recording 1 traces of 1 types on node 32
Recording 1 traces of 1 types on node 69
Recording 1 traces of 1 types on node 9
Recording 0 traces of 0 types on node 51
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 77
Recording 1 traces of 1 types on node 33
Recording 0 traces of 0 types on node 40
Recording 2 traces of 1 types on node 58
Recording 0 traces of 0 types on node 34
Recording 0 traces of 0 types on node 49
Recording 0 traces of 0 types on node 18
Recording 1 traces of 1 types on node 19
Recording 0 traces of 0 types on node 66
Recording 1 traces of 1 types on node 25
Recording 0 traces of 0 types on node 62
Recording 1 traces of 1 types on node 12
Recording 1 traces of 1 types on node 37
Recording 0 traces of 0 types on node 72
Recording 0 traces of 0 types on node 56
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 15
Recording 1 traces of 1 types on node 41
Recording 1 traces of 1 types on node 43
Recording 0 traces of 0 types on node 42
Recording 1 traces of 1 types on node 70
Recording 0 traces of 0 types on node 50
Recording 1 traces of 1 types on node 71
Recording 0 traces of 0 types on node 79
Recording 2 traces of 1 types on node 11
Recording 0 traces of 0 types on node 22
Recording 3 traces of 1 types on node 14
Recording 0 traces of 0 types on node 55
Recording 1 traces of 1 types on node 28
Recording 0 traces of 0 types on node 13
Recording 1 traces of 1 types on node 60
Recording 0 traces of 0 types on node 48
Recording 0 traces of 0 types on node 65
Recording 1 traces of 1 types on node 63
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 7
Recording 0 traces of 0 types on node 68
Recording 0 traces of 0 types on node 78
0.0s

Running simulation for 2500.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
2.1s
2.2s
2.3s
2.4s
2.5s
  Done; run time = 1167.29 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 2.56 s.

Analyzing...
[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m  Cells: 12908
  Connections: 0 (0.00 per cell)
  Spikes: 74134 (2.30 Hz)
  Simulated time: 2.5 s; 80 workers
  Run time: 1167.29 s
[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m[0m   NGF1 
        (1500 - 1750 ms): 1.828 Hz
        (1750 - 2000 ms): 2.199 Hz
        (2000 - 2250 ms): 1.245 Hz
        (2250 - 2500 ms): 2.013 Hz
   IT2 
        (1500 - 1750 ms): 0.249 Hz
        (1750 - 2000 ms): 0.071 Hz
        (2000 - 2250 ms): 0.189 Hz
        (2250 - 2500 ms): 2.047 Hz
   SOM2 
        (1500 - 1750 ms): 11.200 Hz
        (1750 - 2000 ms): 5.600 Hz
        (2000 - 2250 ms): 4.800 Hz
        (2250 - 2500 ms): 20.000 Hz
   PV2 
        (1500 - 1750 ms): 12.308 Hz
        (1750 - 2000 ms): 9.231 Hz
        (2000 - 2250 ms): 5.846 Hz
        (2250 - 2500 ms): 27.385 Hz
   VIP2 
        (1500 - 1750 ms): 24.500 Hz
        (1750 - 2000 ms): 58.750 Hz
        (2000 - 2250 ms): 27.750 Hz
        (2250 - 2500 ms): 58.250 Hz
   NGF2 
        (1500 - 1750 ms): 14.545 Hz
        (1750 - 2000 ms): 10.909 Hz
        (2000 - 2250 ms): 14.909 Hz
        (2250 - 2500 ms): 21.818 Hz
   IT3 
        (1500 - 1750 ms): 0.236 Hz
        (1750 - 2000 ms): 0.063 Hz
        (2000 - 2250 ms): 0.190 Hz
        (2250 - 2500 ms): 0.387 Hz
   SOM3 
        (1500 - 1750 ms): 0.057 Hz
        (1750 - 2000 ms): 0.000 Hz
        (2000 - 2250 ms): 0.000 Hz
        (2250 - 2500 ms): 2.914 Hz
   PV3 
        (1500 - 1750 ms): 6.295 Hz
        (1750 - 2000 ms): 7.773 Hz
        (2000 - 2250 ms): 8.455 Hz
        (2250 - 2500 ms): 12.682 Hz
   VIP3 
        (1500 - 1750 ms): 19.393 Hz
        (1750 - 2000 ms): 34.483 Hz
        (2000 - 2250 ms): 23.166 Hz
        (2250 - 2500 ms): 35.071 Hz
   NGF3 
        (1500 - 1750 ms): 6.187 Hz
        (1750 - 2000 ms): 8.267 Hz
        (2000 - 2250 ms): 6.640 Hz
        (2250 - 2500 ms): 7.040 Hz
   ITP4 
        (1500 - 1750 ms): 0.779 Hz
        (1750 - 2000 ms): 0.249 Hz
        (2000 - 2250 ms): 0.688 Hz
        (2250 - 2500 ms): 1.171 Hz
   ITS4 
        (1500 - 1750 ms): 0.659 Hz
        (1750 - 2000 ms): 0.148 Hz
        (2000 - 2250 ms): 0.559 Hz
        (2250 - 2500 ms): 1.037 Hz
   SOM4 
        (1500 - 1750 ms): 0.333 Hz
        (1750 - 2000 ms): 0.167 Hz
        (2000 - 2250 ms): 0.333 Hz
        (2250 - 2500 ms): 2.667 Hz
   PV4 
        (1500 - 1750 ms): 4.688 Hz
        (1750 - 2000 ms): 6.366 Hz
        (2000 - 2250 ms): 5.333 Hz
        (2250 - 2500 ms): 7.656 Hz
   VIP4 
        (1500 - 1750 ms): 10.154 Hz
        (1750 - 2000 ms): 26.462 Hz
        (2000 - 2250 ms): 15.385 Hz
        (2250 - 2500 ms): 25.846 Hz
   NGF4 
        (1500 - 1750 ms): 8.286 Hz
        (1750 - 2000 ms): 9.714 Hz
        (2000 - 2250 ms): 14.571 Hz
        (2250 - 2500 ms): 14.571 Hz
   IT5A 
        (1500 - 1750 ms): 1.850 Hz
        (1750 - 2000 ms): 3.298 Hz
        (2000 - 2250 ms): 1.560 Hz
        (2250 - 2500 ms): 2.953 Hz
   CT5A 
        (1500 - 1750 ms): 0.123 Hz
        (1750 - 2000 ms): 1.694 Hz
        (2000 - 2250 ms): 0.145 Hz
        (2250 - 2500 ms): 1.504 Hz
   SOM5A 
        (1500 - 1750 ms): 2.047 Hz
        (1750 - 2000 ms): 2.605 Hz
        (2000 - 2250 ms): 1.023 Hz
        (2250 - 2500 ms): 4.558 Hz
   PV5A 
        (1500 - 1750 ms): 3.342 Hz
        (1750 - 2000 ms): 3.288 Hz
        (2000 - 2250 ms): 3.890 Hz
        (2250 - 2500 ms): 6.027 Hz
   VIP5A 
        (1500 - 1750 ms): 14.400 Hz
        (1750 - 2000 ms): 33.200 Hz
        (2000 - 2250 ms): 16.800 Hz
        (2250 - 2500 ms): 43.200 Hz
   NGF5A 
        (1500 - 1750 ms): 5.500 Hz
        (1750 - 2000 ms): 25.000 Hz
        (2000 - 2250 ms): 8.000 Hz
        (2250 - 2500 ms): 29.000 Hz
   IT5B 
        (1500 - 1750 ms): 2.251 Hz
        (1750 - 2000 ms): 7.482 Hz
        (2000 - 2250 ms): 3.244 Hz
        (2250 - 2500 ms): 4.365 Hz
   CT5B 
        (1500 - 1750 ms): 0.068 Hz
        (1750 - 2000 ms): 0.306 Hz
        (2000 - 2250 ms): 0.085 Hz
        (2250 - 2500 ms): 0.144 Hz
   PT5B 
        (1500 - 1750 ms): 0.314 Hz
        (1750 - 2000 ms): 0.255 Hz
        (2000 - 2250 ms): 0.221 Hz
        (2250 - 2500 ms): 0.212 Hz
   SOM5B 
        (1500 - 1750 ms): 13.286 Hz
        (1750 - 2000 ms): 13.250 Hz
        (2000 - 2250 ms): 14.321 Hz
        (2250 - 2500 ms): 13.750 Hz
   PV5B 
        (1500 - 1750 ms): 1.821 Hz
        (1750 - 2000 ms): 1.552 Hz
        (2000 - 2250 ms): 1.851 Hz
        (2250 - 2500 ms): 4.299 Hz
   VIP5B 
        (1500 - 1750 ms): 7.529 Hz
        (1750 - 2000 ms): 9.176 Hz
        (2000 - 2250 ms): 7.765 Hz
        (2250 - 2500 ms): 24.000 Hz
   NGF5B 
        (1500 - 1750 ms): 6.833 Hz
        (1750 - 2000 ms): 22.833 Hz
        (2000 - 2250 ms): 11.333 Hz
        (2250 - 2500 ms): 21.000 Hz
   IT6 
        (1500 - 1750 ms): 0.464 Hz
        (1750 - 2000 ms): 0.991 Hz
        (2000 - 2250 ms): 0.690 Hz
        (2250 - 2500 ms): 1.094 Hz
   CT6 
        (1500 - 1750 ms): 0.476 Hz
        (1750 - 2000 ms): 1.166 Hz
        (2000 - 2250 ms): 0.611 Hz
        (2250 - 2500 ms): 1.249 Hz
   SOM6 
        (1500 - 1750 ms): 29.397 Hz
        (1750 - 2000 ms): 51.683 Hz
        (2000 - 2250 ms): 36.698 Hz
        (2250 - 2500 ms): 49.397 Hz
   PV6 
        (1500 - 1750 ms): 0.238 Hz
        (1750 - 2000 ms): 3.571 Hz
        (2000 - 2250 ms): 3.619 Hz
        (2250 - 2500 ms): 3.667 Hz
   VIP6 
        (1500 - 1750 ms): 21.667 Hz
        (1750 - 2000 ms): 10.000 Hz
        (2000 - 2250 ms): 13.333 Hz
        (2250 - 2500 ms): 2.333 Hz
   NGF6 
        (1500 - 1750 ms): 38.000 Hz
        (1750 - 2000 ms): 92.316 Hz
        (2000 - 2250 ms): 48.842 Hz
        (2250 - 2500 ms): 82.000 Hz
   TC 
        (1500 - 1750 ms): 4.345 Hz
        (1750 - 2000 ms): 5.207 Hz
        (2000 - 2250 ms): 5.276 Hz
        (2250 - 2500 ms): 5.483 Hz
   TCM 
        (1500 - 1750 ms): 4.800 Hz
        (1750 - 2000 ms): 4.284 Hz
        (2000 - 2250 ms): 4.000 Hz
        (2250 - 2500 ms): 4.697 Hz
   HTC 
        (1500 - 1750 ms): 3.263 Hz
        (1750 - 2000 ms): 3.684 Hz
        (2000 - 2250 ms): 3.053 Hz
        (2250 - 2500 ms): 4.737 Hz
   IRE 
        (1500 - 1750 ms): 2.194 Hz
        (1750 - 2000 ms): 3.561 Hz
        (2000 - 2250 ms): 3.252 Hz
        (2250 - 2500 ms): 3.690 Hz
   IREM 
        (1500 - 1750 ms): 1.419 Hz
        (1750 - 2000 ms): 4.232 Hz
        (2000 - 2250 ms): 3.277 Hz
        (2250 - 2500 ms): 4.052 Hz
   TI 
        (1500 - 1750 ms): 2.588 Hz
        (1750 - 2000 ms): 0.863 Hz
        (2000 - 2250 ms): 1.804 Hz
        (2250 - 2500 ms): 1.725 Hz
   TIM 
        (1500 - 1750 ms): 3.765 Hz
        (1750 - 2000 ms): 1.804 Hz
        (2000 - 2250 ms): 2.902 Hz
        (2250 - 2500 ms): 3.529 Hz
Saving output as data/v34_batch25/trial_2142/trial_2142.pkl ... 
Finished saving!
  Done; saving time = 3.35 s.
Plotting raster...
Plotting recorded cell traces ... trace
  Done; plotting time = 20.07 s

Total time = 1900.08 s

End time:  2021-07-04 07:29:57.167836
[0m